# Generated by Django 5.2.4 on 2025-07-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('code_pin', models.CharField(max_length=6)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
