# Generated by Django 5.2.4 on 2025-07-15 12:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destinataire', models.CharField(max_length=20)),
                ('reseau', models.CharField(max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_wave', models.CharField(max_length=20)),
                ('methode_paiement', models.CharField(choices=[('wave', 'Wave'), ('points', 'Points')], max_length=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_ussd', models.CharField(blank=True, max_length=100, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfert.utilisateur')),
            ],
        ),
    ]
